Login and Create Account
Pranaav003/NewsWebApp pull request #1
Opened 2024-10-10 18:06 UTC by jude-lieb

Initial html pages for logging in that include form verification.

2024-10-10 18:21 UTC, zeshengchen requested changes

2024-10-10 18:21 UTC, zeshengchen commented on newsApp/login/createAccount.html
> +    <script type="text/javascript">
please move javascript to a separate file. moreover, consider to how to organize the project. For example, under root, there may have two folders: one for "frontend" and the other for "backend". For "frontend", there maybe has a folder to store "css" and the other to store "javascript" code.

2024-10-10 18:21 UTC, zeshengchen commented on newsApp/login/login.html
> +    <script type="text/javascript">
move javascript code into a different file.

2024-10-10 23:45 UTC, zeshengchen approved these changes

2024-10-11 00:37 UTC, Pranaav003 approved these changes

2024-10-11 00:37 UTC, merged

2024-10-11 00:51 UTC, zeshengchen commented
@Pranaav003 for future pull requests, please wait until all group members approve it and then complete. For this pull request, @cgibson1421 has not approved it yet.

Moreover, please let who creates the pull request to complete it.